### ISSUE TITLE
Staging Delay

### ISSUE THREAD

**Issue by schnip** [jberkman/kOSScripts#4]
On line 56 of dd_launch there is a two second delay between the thrust of a stage dying off and the next stage being initiated. I am curious as to the reasoning of the delay being that long.

**Comment by jberkman** [comment]
real rockets have delays between stages. for example, a delta IV can have a six second delay between MECO and stage separation, and another 14 seconds before second stage ignition.

it gives time for fairings or the old stage to fall away before igniting the next stage.
